### ISSUE TITLE
pkg-config file is broken when CMAKE_INSTALL_LIBDIR is absolute

### ISSUE THREAD

**Issue by alexshpilkin** [wdas/SeExpr#106]
As per title: `src/build/seexpr2.pc.in` has
```
prefix=@CMAKE_INSTALL_PREFIX@
libdir=${prefix}/@CMAKE_INSTALL_LIBDIR@
```
and so can’t handle absolute paths in `CMAKE_INSTALL_LIBDIR`. This leads to broken .pc files on NixOS in particular.

See “[Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files)” for a thorough discussion of the problem and a suggested fix, or [KDE’s extra-cmake-modules](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/modules/ECMGeneratePkgConfigFile.cmake#L166) for a simpler approach.

**Comment by davvid** [comment]
Thanks for the pointers. If I'm understanding correctly, `libdir=@CMAKE_INSTALL_FULL_LIBDIR@` would be the correct setup, is that correct?

**Comment by alexshpilkin** [comment]
@davvid That is the simplest solution, except it sacrifices relocatability, which some people [apparently](https://github.com/libjxl/libjxl/issues/1400#issuecomment-1122183126) depend on. I don’t actually know if this is important here; if so, the solution from KDE (check with `if (IS_ABSOLUTE ...)` and either prepend `${prefix}/` or set as is) can be used.

**Comment by davvid** [comment]
Checking if the libdir is absolute and then conditionally prepending sounds like the way to go.

**Comment by davvid** [comment]
https://github.com/wdas/SeExpr/commit/b2656fbacf59eb8e2bcee8aefb39d40eb76ec94b added the IS_ABSOLUTE checks and variables used by https://github.com/wdas/SeExpr/commit/aad54f0dfe0de173e2c4e7d3c7df3b1a61e5ab31
