### ISSUE TITLE
Incorrectly duplicated code

### ISSUE THREAD

**Issue by ikolev21** [wdas/SeExpr#107]
In `src/SeExpr2/UI/ExprCurve.cpp` , `ExprCurve::openDetail()`, lines 432-439 are verbatim copy of lines 423-430.

This looks like a copy-paste bug, I don't see any reason why the block of code within `if (dialog->exec() == QDialog::Accepted)` should be repeated twice.

**Comment by davvid** [comment]
Thanks for the heads-up!
