### ISSUE TITLE
Oddness building on CentOS 6.5

### ISSUE THREAD

**Issue by chippey** [wdas/SeExpr#16]
So, I've run into a very odd hiccup building on CentOS 6.5, as the subject says - 
Cloning in a vanilla repo from github, and following the build instructions for the impatient (making a blank build dir and running cmake in it), I get 83% of the build progress when I get

```
make[2]: *** No rule to make target `src/SeExpr/libSeExpr.so', needed by `src/SeExprEditor/libSeExprEditor.so'.  Stop.
make[1]: *** [src/SeExprEditor/CMakeFiles/SeExprEditor.dir/all] Error 2
make:  *** [all] Error 2
```

A bit of digging reveals that there's no libSeExpr.so in src/SeExpr (in the build dir), which is odd as further up in the build progress (at about 15% of the way through), the log shows:

```
Linking CXX shared library libSeExpr.so
```

going directly into the src/SeExpr dir (in the build dir), and running make (with the cmake generate Makefile) there does build the vanished libSeExpr.so

(ie, 

```
cd src/SeExpr
make
```

)
produces the library and seems to fix the problem.

From there I can go back to the base build and finish building no problem (

```
cd ../..
make install
```

)

I've got a fairly vanilla CentOS 6.5 install, with an except that I'm building with gcc 4.1.2 (but this vanishing behaviour also is exhibited with gcc 4.4.7-4 (the one that's packaged with CentOS 6.5)).

To be clear, I'm able to build and use SeExpr in the end (woohoo!), but though you might like to be aware of the odd hoop I jumped through to do it.

Cheers!
-Matt

**Comment by davvid** [comment]
This should be a non-issue with the latest cmake updates.  Please reopen if you still see this.
