### ISSUE TITLE
texture reading functions not a part of the distribution?

### ISSUE THREAD

**Issue by ssteinbach** [wdas/SeExpr#3]
Hey Guys,

In the docs, you mention:
Texture Lookup Functions
vector map( string filename, [float format-arg], [float u, float v], [int channel] )
Access a texture map.
Note: strings must be enclosed in single or double quotes.

vector projmap ( string coordspace, string type, string filename, [float format-arg] )
Projects a texture map from the given named coordinace space using the specified projection type.

However, I can't seem to access these from the renderman shadeop.  Is this a build issue?

I did some grepping and couldn't find any references other than the docs in the distributed source, either, so maybe it was not included in the source distribution?

thanks guys!
-Stephan.

**Comment by jberlin** [comment]
Closing this issue -- the latest docs no longer reference texture lookup functions.
