### ISSUE TITLE
New version release please?

### ISSUE THREAD

**Issue by danfe** [wdas/SeExpr#34]
Currently there is only one official release, **1.0.1** from May 4 2013, which is quite old and missing features required by modern applications (e.g. `libSeExprEditor.so`).  While pulling from git is not a problem for personal development, packagers for GNU/Linux and FreeBSD prefer to work with specific versions (or at least tagged commits).  Otherwise the only option is to embed commit dates in package versions which is not very convenient.

**Comment by aselle** [comment]
Yes, this can definitely be done.

**Comment by danfe** [comment]
Now that new releases are appearing pretty regularly, I'm closing this issue.
