### ISSUE TITLE
Help - Compiling SeExpr 

### ISSUE THREAD

**Issue by SheepDomination** [wdas/SeExpr#42]
Hi, I've downloaded the cMake build of SeExpr, I've also installed cMake including Python and PyQT as I was informed I needed PyQT as well installed ? 

I choose the folder or sub-folders where the cMake files are located in Windows, I choose the folder where to build the binaries I have Sublime Text 2 - MinGW MakeFiles as the Current Generator as I have sublime text 2 installed but I get the error the project files are invalid ?

Ps. Is SeExprMeshMaya still available for Maya 2015/2016 ?

**Comment by jberlin** [comment]
If you're building for windows, you might take a look at the info on this related issue: [https://github.com/wdas/SeExpr/issues/14](url)

**Comment by SheepDomination** [comment]
The link you supplied is a 404 ?

**Comment by davvid** [comment]
#14 is the referenced issue

**Comment by SheepDomination** [comment]
I posted my question on the Google Group.
