### ISSUE TITLE
Issues building on Centos 7

### ISSUE THREAD

**Issue by varomix** [wdas/SeExpr#68]
Hi

I have no idea why this is failing
please help thank 

> [ 81%] Building CXX object src/ui/CMakeFiles/expreditor2.dir/sipexpreditor2part0.o
cd /home/varomix/dev/SeExpr/build/src/ui && /usr/bin/c++   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Dexpreditor2_EXPORTS -std=c++11 -O3 -DNDEBUG -fPIC -I/home/varomix/dev/SeExpr/src/EditorUI -I/home/varomix/dev/SeExpr/src/SeExpr -I/home/varomix/dev/SeExpr/build/src/SeExpr -I/home/varomix/dev/SeExpr/build/include -I/home/varomix/dev/SeExpr/src/ui -I/home/varomix/dev/SeExpr/src/ui/CE -I/usr/include/python2.7 -I/usr/share/sip/PyQt4 -I/usr/include/QtCore -I/usr/include/QtGui     -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wall -Wextra -Wno-unused-parameter -pthread -o CMakeFiles/expreditor2.dir/sipexpreditor2part0.o -c /home/varomix/dev/SeExpr/build/src/ui/sipexpreditor2part0.cpp
./sipexpreditor2part0.cpp:3409:1: error: too many initializers for ‘sipClassTypeDef {aka _sipClassTypeDef}’
 };
 ^
./sipexpreditor2part0.cpp:6380:1: error: too many initializers for ‘sipClassTypeDef {aka _sipClassTypeDef}’
 };
 ^
./sipexpreditor2part0.cpp:9362:1: error: too many initializers for ‘sipClassTypeDef {aka _sipClassTypeDef}’
 };
 ^
./sipexpreditor2part0.cpp:12344:1: error: too many initializers for ‘sipClassTypeDef {aka _sipClassTypeDef}’
 };
 ^
./sipexpreditor2part0.cpp:16079:1: error: too many initializers for ‘const pyqt4QtSignal {aka const _pyqt4QtSignal}’
 };
 ^
./sipexpreditor2part0.cpp:16079:1: error: too many initializers for ‘const pyqt4QtSignal {aka const _pyqt4QtSignal}’
./sipexpreditor2part0.cpp:16200:1: error: too many initializers for ‘sipClassTypeDef {aka _sipClassTypeDef}’
 };
 ^
./sipexpreditor2part0.cpp:19624:1: error: too many initializers for ‘const pyqt4QtSignal {aka const _pyqt4QtSignal}’
 };
 ^
./sipexpreditor2part0.cpp:19624:1: error: too many initializers for ‘const pyqt4QtSignal {aka const _pyqt4QtSignal}’
./sipexpreditor2part0.cpp:19678:1: error: too many initializers for ‘sipClassTypeDef {aka _sipClassTypeDef}’
 };
 ^
./sipexpreditor2part0.cpp:22913:1: error: too many initializers for ‘sipClassTypeDef {aka _sipClassTypeDef}’
 };
 ^
./sipexpreditor2part0.cpp:26165:1: error: too many initializers for ‘const pyqt4QtSignal {aka const _pyqt4QtSignal}’
 };
 ^
./sipexpreditor2part0.cpp:26165:1: error: too many initializers for ‘const pyqt4QtSignal {aka const _pyqt4QtSignal}’
./sipexpreditor2part0.cpp:26165:1: error: too many initializers for ‘const pyqt4QtSignal {aka const _pyqt4QtSignal}’
./sipexpreditor2part0.cpp:26219:1: error: too many initializers for ‘sipClassTypeDef {aka _sipClassTypeDef}’
 };
 ^
./sipexpreditor2part0.cpp:29189:1: error: too many initializers for ‘sipClassTypeDef {aka _sipClassTypeDef}’
 };
 ^
./sipexpreditor2part0.cpp:32353:1: error: too many initializers for ‘const pyqt4QtSignal {aka const _pyqt4QtSignal}’
 };
 ^
./sipexpreditor2part0.cpp:32353:1: error: too many initializers for ‘const pyqt4QtSignal {aka const _pyqt4QtSignal}’
./sipexpreditor2part0.cpp:32353:1: error: too many initializers for ‘const pyqt4QtSignal {aka const _pyqt4QtSignal}’
./sipexpreditor2part0.cpp:32442:1: error: too many initializers for ‘sipClassTypeDef {aka _sipClassTypeDef}’
 };
 ^
make[2]: *** [src/ui/CMakeFiles/expreditor2.dir/sipexpreditor2part0.o] Error 1
make[2]: Leaving directory `/home/varomix/dev/SeExpr/build'
make[1]: *** [src/ui/CMakeFiles/expreditor2.dir/all] Error 2
make[1]: Leaving directory `/home/varomix/dev/SeExpr/build'
make: *** [all] Error 2

>

**Comment by ix-dcourtois** [comment]
Seems you have an incorrect version of Python, sip and/or PyQt.
I had those errors, but I fixed my setup since, and I don't remember exactly how.

Which version of Python and sip do you have ? (`yum list python` and `yum list sip`)
