### ISSUE TITLE
pnoise function sending SIGFPE from noiseHelper

### ISSUE THREAD

**Issue by nrusch** [wdas/SeExpr#7]
Hello,

I've been doing some work integrating SeExpr into another application, and I've encountered a consistent case where the (SeExpr) pnoise function will cause the library to throw SIGFPE if any component of the 'period' vector is less than 1, taking down the host application. A quick gdb backtrace seems to indicate its origin as SeExpr::noiseHelper.

Does the library expect a host application or wrapping library to handle things like this? Or does it sound like an edge-case bug?

Thanks,

-Nathan

**Comment by jberlin** [comment]
Closing this issue -- pnoise() now clamps the period at 1 and above.
