### ISSUE TITLE
llvm8 droped 'TypeBuilder'

### ISSUE THREAD

**Issue by bartoszek** [wdas/SeExpr#93]
As of `llvm=8.0` Type Builder was deprecated and removed [+++](https://github.com/llvm/llvm-project/commit/c0044118c8ec4889ff1490179d5d70549cb7621c)
Could we have it removed to keep compatibility with new llvm...

**Comment by davvid** [comment]
Sure thing, that's a reasonable request.  We recently added some backcompat stuff for LLVM that would check the version and do the right thing.  Do you think you can try something like that to get the new API working?

Please see fcd7289c57a6ef30807e38a9eaad8b0dc3417f05 for an example showing how we did it for `llvm::AttributeList::FunctionIndex`.  I'd have to try llvm8 on my home debian machine but if you happen to have it handy then a PR would be much appreciated.

**Comment by davvid** [comment]
Thanks for the report.  I've removed the dependency on TypeBuilder, and added Python3 compatibility as well.  cheers
